name: shared_ui

resolution: workspace

version: 0.0.1+1

environment:
  sdk: '>=3.8.0 <4.0.0'

flutter:
  assets:
    - assets/images/
  fonts:
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: RobotoLight
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf